# Generated by Django 3.2.7 on 2021-10-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='packing',
        ),
        migrations.AddField(
            model_name='driver',
            name='can_accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RequiredClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.classification')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.request')),
            ],
        ),
    ]
