# Generated by Django 3.2.7 on 2022-05-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
    ]
