# Generated by Django 3.2.7 on 2022-05-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='year',
            field=models.CharField(max_length=70),
        ),
    ]
