# Generated by Django 3.2.7 on 2022-05-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_carrier_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='TripStatus',
        ),
    ]
